version: '3'
services:
  flasky:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    restart: always
    links:
      - postgres:dbserver
  postgres:
    image: "postgres:10"
    env_file: .env-postgres
    restart: always